[package]
name = "yieldstat_rs"
version = "0.1.0"
authors = ["Michael Berg <michael.berg@zalf.de>"]

[dependencies]
#rusqlite = "0.15.0"
time = "0.1.40"

[dependencies.rusqlite]
version = "0.15.0"
features = ["bundled"]